---
title: "Untitled"
author: "Álvaro Domingo"
date: "2023-09-27"
output: pdf_document
---
```{r}
library(corrplot)
library(dplyr)
```

## Read data

```{r}
df = read.csv("../../data/raw/form_answers.csv")
names(df) = c("timestamp", "role", "experience_general", "experience_environment", "experience_monitor", "experience_reduce", "framework", "useful_monitor", "useful_reduce", "ease_use", "ease_learn", "intent_use", "extra", "comment", "mail")
df = df[-12,]  # remove invalid answer
#df[df == "Not sure"] = NaN
df[8:12] = lapply(df[8:12], as.integer)
for(i in 8:12){
  df[is.na(df[,i]), i] <- as.integer(mean(df[,i], na.rm = TRUE))
}
```

## Explore correlations

```{r}
prop.table(table(df$role))
prop.table(table(df$framework))
colMeans(df[3:6])
colMeans(df[8:12])
```



```{r}
df[c(3:12)] %>% group_by(framework) %>% summarise_all(mean)
```


```{r}
df[7] = as.integer(factor(df[,7]))
cor_matrix = cor(df[c(3:12)], method = "spearman")
#cor_framework = sapply(df[c(3:6, 8:12)], function(x) cor(df[,7], x, method = "pearson"))

corrplot(cor_matrix, method="color", outline="white")
print(mean(cor_matrix[6:10,6:10][lower.tri(cor_matrix[5:9,5:9])]))
print(mean(cor_matrix[6:10,1:4]))
```


